import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import AuthProvider from "./providers/AuthProvider";
import StoreProvider from "./StoreProvider";
import Snackbar from "./components/Snackbar/Snackbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Manga Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="flex h-screen flex-col justify-between ">
          <StoreProvider>
            <AuthProvider>
              <Snackbar />
              <Navbar />
              {children}
              <Footer />
            </AuthProvider>
          </StoreProvider>
        </main>
        <div id="snackbar__root" className="relative"></div>
      </body>
    </html>
  );
}
